baseURL = 'https://carrot.tw/'
languageCode = 'en-us'
title = 'Carrot'
theme = "PaperMod"

[params.assets]
        favicon = "/favicon.png"
[params.profileMode]
    enabled = true
    title = "我是一根蘿蔔🥕"
 [[menu.main]]
    name = "首頁"
    url = "/"
    weight = 10

[[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 20

[[menu.main]]
    name = "🎹"
    url = "/"
    weight = 30
 
[[menu.main]]
    name = "關於"
    url = "/"
    weight = 40


