baseURL = 'https://carrot.tw/'
languageCode = 'zh-tw'
title = 'Carrot'
theme = "PaperMod"
hasCJKLanguage = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML"]

[params]
 
  defaultTheme = "dark"
  ShowReadingTime = true   
  ShowShareButtons = false   
  ShowCodeCopyButtons = true

[params.assets]
        favicon = "/favicon.png"

[params.profileMode]
    enabled = true
    title = "我是一根蘿蔔🥕"

 [[menu.main]]
    name = "🥕"
    url = "/"
    weight = 10

[[menu.main]]
    name = "📝"
    url = "/posts/"
    weight = 20




[[menu.main]]
    name = "🎲"
    url = "/random/"
    weight = 50

[[menu.main]]
    name = "🔎"
    url = "/search/"
    weight = 60

[params.searchApp]
    limit = 20          
    showScores = false
    secure = false
    mainSections = ["posts"]

