baseURL = 'https://carrot.tw/'
languageCode = 'zh-tw'
title = 'Carrot Blog'
theme = "PaperMod"
hasCJKLanguage = true
timeZone = "Asia/Taipei"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML"]

[params]
  defaultTheme = "dark"
  ShowReadingTime = true   
  ShowShareButtons = false   
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowWordCount = true
  hideMeta = false
  ShowBreadCrumbs = true
  images = ["/share.png"]
  math = true
[params.label]
  text = "Carrot" 
  textWithIcon = false

[params.assets]
  favicon = "/favicon.png"
  favicon32x32 = "/favicon.png"
  apple_touch_icon = "/apple-touch-icon.png"

[params.profileMode]
  enabled = true
  title = "我是一根蘿蔔🥕"

[minify]
  minifyOutput = true
  disableXML = false

[[menu.main]]
  name = "🥕"
  url = "/"
  weight = 10

[[menu.main]]
  name = "📝"
  url = "/posts/"
  weight = 20

[[menu.main]]
  name = "📚"
  url = "/books/"
  weight = 30

[[menu.main]]
  name = "🎹"
  url = "https://www.youtube.com/@carrot603/"
  weight = 40

[[menu.main]]
    name = "👤"
    url = "/posts/about/"
    weight = 50

[[menu.main]]
    name = "💡"
    url = "/now/"
    weight = 60

[[menu.main]]
  name = "🎲"
  url = "/random/"
  weight = 70

[[menu.main]]
  name = "🔎"
  url = "/search/"
  weight = 80

[params.searchApp]
  limit = 20          
  showScores = false
  secure = false
  mainSections = ["posts"]
