name: "定時自動編譯與發布"

on:
  schedule:
   
    - cron: '0 21 * * *'
  
  
  workflow_dispatch:

jobs:
  trigger-cloudflare:
    runs-on: ubuntu-latest
    steps:
      - name: "通知 Cloudflare Pages 重新編譯與發布"
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/84bc2165-18d8-4674-8519-10a4a0ba7062"
